-- ============================================================
-- GOAL BADGES — artwork on collector goals, plus the five goal
--     types that can be measured from data the app already has.
--
--     WHAT THIS DOES NOT DO: it does not touch a single existing
--     goal's type or config, and it does not delete anything. The
--     goals already on the board keep working exactly as they are;
--     three of them simply gain artwork.
--
--     Safe to re-run.
-- ============================================================


-- ============================================================
-- 1. ARTWORK ON A GOAL
--    A path under assets/goal-badges/. Null means "no art yet",
--    and the app falls back to the emoji, so a goal added from the
--    admin panel without a badge still looks like something.
-- ============================================================
alter table public.collector_goal_templates
  add column if not exists badge_image text;


-- ============================================================
-- 2. THE FIVE NEW GOAL TYPES
--    Every one reads data that was already being stored:
--      graded_count / grade_ladder  -> user_cards.condition, which has
--        held "PSA 10" style values since the Card Lookup grade rail
--      added_in_month / monthly_streak -> user_cards.added_at, on the
--        table since day one and simply never read
--      value_total -> profiles.collection_value
--    No new tables. No new columns on user_cards. Nothing to backfill.
--
--    The check constraint is found by definition rather than by name,
--    because its name was generated by Postgres and differs between
--    databases.
-- ============================================================
do $$
declare c text;
begin
  select conname into c
    from pg_constraint
   where conrelid = 'public.collector_goal_templates'::regclass
     and contype = 'c'
     and pg_get_constraintdef(oid) ilike '%goal_type%';
  if c is not null then
    execute format('alter table public.collector_goal_templates drop constraint %I', c);
  end if;
end $$;

alter table public.collector_goal_templates
  add constraint collector_goal_templates_goal_type_check
  check (goal_type in (
    'pokedex_range', 'full_pokedex', 'generation', 'type', 'pokemon',
    'set_completion', 'master_set', 'rarity', 'artist', 'chase_list',
    'graded_count', 'grade_ladder', 'added_in_month', 'monthly_streak',
    'value_total', 'custom_manual'
  ));


-- ============================================================
-- 3. ARTWORK FOR THREE GOALS THAT ALREADY EXIST
--    Matched by name. Nothing else about these rows changes.
-- ============================================================
update public.collector_goal_templates
   set badge_image = 'assets/goal-badges/set-complete.webp'
 where name = 'Scarlet & Violet—151 Set';

update public.collector_goal_templates
   set badge_image = 'assets/goal-badges/master-set.webp'
 where name = 'Pokémon 151 Master Set';

update public.collector_goal_templates
   set badge_image = 'assets/goal-badges/regional-pokedex.webp'
 where name = 'Complete Generation I';


-- ============================================================
-- 4. THE FIVE NEW GOALS
--    Each one finishes. That matters more than it sounds: a badge
--    that can never light up is worse than no badge, so nothing goes
--    on the board here without a finish line the app can see.
-- ============================================================
insert into public.collector_goal_templates
  (name, description, icon, badge_image, badge_text, goal_type, config, display_order, enabled)
values
  ('Gem Mint Ten',
   'Own ten different cards graded a perfect 10.',
   '🔟', 'assets/goal-badges/gem-mint-ten.webp', '🏆 Gem Mint Ten',
   'graded_count', '{"grade":10,"target":10}'::jsonb, 11, true),

  ('Grade Ladder',
   'Own the same card in every grade from 1 through 10.',
   '🪜', 'assets/goal-badges/grade-ladder.webp', '🏆 Grade Ladder',
   'grade_ladder', '{}'::jsonb, 12, true),

  ('Monthly Momentum',
   'Add 25 different cards to your collection in one calendar month.',
   '📅', 'assets/goal-badges/monthly-momentum.webp', '🏆 Monthly Momentum',
   'added_in_month', '{"target":25}'::jsonb, 13, true),

  ('Yearlong Collector',
   'Add at least one card every month for twelve months in a row.',
   '🗓️', 'assets/goal-badges/yearlong-collector.webp', '🏆 Yearlong Collector',
   'monthly_streak', '{"months":12}'::jsonb, 14, true),

  ('Value Milestone',
   'Grow your collection to a total value of $1,000.',
   '📈', 'assets/goal-badges/value-milestone.webp', '🏆 Value Milestone',
   'value_total', '{"target":1000}'::jsonb, 15, true)

on conflict (name) do update
  set description  = excluded.description,
      icon         = excluded.icon,
      badge_image  = excluded.badge_image,
      badge_text   = excluded.badge_text,
      goal_type    = excluded.goal_type,
      config       = excluded.config,
      enabled      = excluded.enabled;


-- ============================================================
-- 5. CHECK — the goals carrying artwork, in board order.
-- ============================================================
select display_order, name, goal_type, badge_image, enabled
  from public.collector_goal_templates
 where badge_image is not null
 order by display_order;
